---

- name: Install example application
  yum:
    name: httpd
    state: latest

- name: Configure example application
  shell: "echo 'Example app' > /var/www/html"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Clear bash history
  shell: history -c

